# Generated by Django 3.0.6 on 2020-05-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('heading', models.CharField(max_length=50)),
                ('content', models.TextField()),
                ('date', models.DateTimeField(blank=True)),
            ],
        ),
    ]
