# Generated by Django 3.0.6 on 2020-06-01 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_feed_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='slug',
            field=models.SlugField(max_length=140, unique=True),
        ),
    ]
